# vim:sw=2:et:
os: linux
dist: xenial

language: erlang
notifications:
  email:
    on_success: never
    on_failure: always

otp_release:
  - "21.3"
  - "22.3"

before_script:
  # We force the hostname to be "localhost" for the common_test node.
  # This fixes an issue where Erlang fails to start a slave node in
  # coordination_SUITE if the hostname is the real one (it times out).
  - sed -E -i'' -e 's/(-sname ct_\$\(PROJECT\))/\1@localhost/' erlang.mk

script:
  - make xref
  - make check
