# vim:sw=2:et:
dist: bionic

sudo: false

language: erlang
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  apt: true

otp_release:
  - "22.2.8"
  - "21.3.8"

script:
  - make xref
  - make check
