name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        otp:
        - "23.2"
        - "24.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{ matrix.otp }}
    - name: XREF
      run: make xref
    - name: DEPS
      run: make test-deps
    - name: DIALYZE
      run: make dialyze
    - name: BUILD
      run: make test-build
    - name: EUNIT
      run: make eunit
    - name: COMMON TEST
      run: make ct
    - name: PROPER
      run: make proper
    - name: CAPTURE TEST LOGS ON FAILURE
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ct-logs-${{matrix.otp}}
        path: logs/*